theme: jekyll-theme-slate
title: craiglowson.github.io
description: Personal blog!

defaults:
    -
      scope:
        path: ""
        type: "pages"
      values:
        layout: "default"
    -
      scope:
        path: ""
        type: "posts" # previously `page` in Jekyll 2.2.
      values:
        layout: "post" # overrides previous default layout
        author: "Craig"